[package]
name = "consistent_hashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
consistent_hash = "0.1.4"
sha-1 = "0.8.1"
hex-literal="0.3.4"