[package]
name = "consistent_hashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
consistent_hash = "0.1.4"

hex-literal="0.3.4"
rust-crypto="0.2.36"